ci/jobs/integration/aws-clive-integration.yml
ci/jobs/preprod/aws-clive-preprod.yml
ci/jobs/production/aws-clive-production.yml
ci/jobs/qa/aws-clive-qa.yml

fix error where default workspace was used instead of the current one

use correct workspace for each env

---

local.tf
variables.tf

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

change instance types and capacity reservations:

---

ci/groups.yml
ci/jobs/development/clear-dynamodb-row-development.yml
ci/jobs/integration/clear-dynamodb-row-integration.yml
ci/jobs/preprod/clear-dynamodb-row-preprod.yml
ci/jobs/production/clear-dynamodb-row-production.yml
ci/jobs/qa/clear-dynamodb-row-qa.yml
ci/jobs/update-pipeline.yml
ci/meta.yml
ci/resources.yml

Add clear dynamodb row jobs and make pipeline self updating

Add clear dynamodb row jobs and make pipeline self updating

---

data.tf

allow Clive to create its own prefix by giving permissions to data prefix

Create clive prefix

---

bootstrap_actions/status_metrics.sh

Signed-off-by: Mark <mark.stevens@infinityworks.com>

added missing variable

---

ci/jobs/aws-clive-pr.yml

TF fmt and add to pipeline

---

ci/jobs/aws-clive-pr.yml
ci/jobs/development/aws-clive-development.yml
ci/jobs/integration/aws-clive-integration.yml
ci/jobs/preprod/aws-clive-preprod.yml
ci/jobs/production/admin/start-cluster.yml
ci/jobs/production/aws-clive-production.yml
ci/jobs/qa/aws-clive-qa.yml
ci/meta.yml
ci/resources.yml
variables.tf

add ami as resource and filter for x86 version. 
remove default tf var for ami id

Pin to non arm ami

---

ci/jobs/aws-clive-pr.yml
outputs.tf
security_groups.tf

Lambda output for Azkaban to use

Lambda output for Azkaban to use

---

ci/jobs/development/admin/start-cluster.yml
ci/jobs/production/admin/start-cluster.yml
ci/meta.yml

Signed-off-by: Connor Avery <ConnorAvery@digital.uc.dwp.gov.uk>

Changes to automatically run Clive for this weekend only

---

ci/jobs/development/admin/start-cluster.yml
ci/jobs/production/admin/start-cluster.yml
ci/meta.yml

Revert "Changes to automatically run Clive for this weekend only"

---

hive_metastore_connectivity.tf

Replace the rules moved from internal compute

Replace the rules moved from internal compute

---

bootstrap_actions.tf
local.tf
outputs.tf
private_dns.tf
terraform.tf.j2

More the service discovery to repo

More the service discovery to repo

---

ci/jobs/aws-clive-pr.yml
ci/meta.yml
ci/vars.yml
create-workspace.yml
data.tf
outputs.tf
terraform.tf.j2

TF13 and missing vars file

---

ci/vars.yml

Latest EMR launcher for testing purposes in Clive

Latest EMR launcher for testing purposes in Clive

---

ci/vars.yml

Release v33 to prod

---

aviator.yml
ci/groups.yml
ci/jobs/ami-test/apply-and-test-with-ami.yml
ci/jobs/aws-clive-pr.yml
ci/jobs/development/aws-clive-development.yml
ci/jobs/integration/aws-clive-integration.yml
ci/jobs/preprod/aws-clive-preprod.yml
ci/jobs/production/aws-clive-production.yml
ci/jobs/qa/aws-clive-qa.yml
ci/meta.yml
ci/resources.yml

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

run ami tests in this pipeline

---

emr-launcher.tf
emr-relauncher.tf

Use log level for lambdas

---

bootstrap_actions/update_dynamo.sh

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

fix update dynamo bug

---

ci/vars.yml
local.tf

Signed-off-by: Connor Avery <ConnorAvery@digital.uc.dwp.gov.uk>

Update non capacity reservation region

---

ci/vars.yml
emr_jobflow_role.tf

Signed-off-by: levankirvalidze <levankirvalidze@digital.uc.dwp.gov.uk>

put back ec2 role, helps with log creation and possibly emrfs
